// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center_image': string;
  'footer': string;
  'hero': string;
}
export const cssExports: CssExports;
export default cssExports;
