// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'team': string;
  'team2': string;
  'team2__button': string;
}
export const cssExports: CssExports;
export default cssExports;
