// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flip_link': string;
  'main': string;
  'slide_in': string;
}
export const cssExports: CssExports;
export default cssExports;
