// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrows': string;
  'arrows__button': string;
  'card': string;
  'card__image': string;
  'card__text': string;
  'carousel': string;
  'content': string;
  'header': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
