// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'arrow__icon': string;
  'heading': string;
  'image': string;
  'link': string;
  'subheading': string;
}
export const cssExports: CssExports;
export default cssExports;
