// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'main': string;
  'mask': string;
}
export const cssExports: CssExports;
export default cssExports;
