// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__button': string;
  'input': string;
  'input__icon': string;
  'main': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
