// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'horizontal_scroll': string;
  'image': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
