// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'a': string;
  'background_heading': string;
  'heading': string;
  'image': string;
  'question-mark': string;
  'question_mark': string;
}
export const cssExports: CssExports;
export default cssExports;
