// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hero': string;
  'logo': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
